# Generated by Django 4.1.7 on 2023-03-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_material_productmaterial_products_sales_salesitems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='code',
        ),
    ]
