# Generated by Django 4.1.7 on 2023-03-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0003_remove_sales_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='code',
            field=models.CharField(default='Not have', max_length=100),
        ),
    ]
