# Generated by Django 4.1.7 on 2023-03-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_employees_products_sales_salesitems_bills_billitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
