# Generated by Django 4.1.7 on 2023-03-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0003_bills_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='itemcount',
            field=models.IntegerField(default=0),
        ),
    ]
