# Generated by Django 4.1.7 on 2023-03-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_employees_billhold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billhold',
            name='salesItems_id',
        ),
        migrations.AddField(
            model_name='billhold',
            name='text',
            field=models.CharField(default='nothing', max_length=10),
        ),
    ]
